-- Find total customers by country.
SELECT 
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country;

-- Find total customers by gender.
SELECT 
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender;

-- Find total products by category
SELECT
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category;

-- What is the average cost in each category?
SELECT
category,
AVG(product_cost) AS avg_cost
FROM gold.dim_products
GROUP BY category;

-- What is the total revenue generated for each category?
SELECT
category,
SUM(sales_amount) AS total_sales
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
ON f.product_key = p.product_key
GROUP BY category;

-- Find total revenue generated by each customer.
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(sales_amount) AS total_sales
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON f.customer_key = c.customer_key
GROUP BY 1,2,3;

-- What is the distribution of sold items across countries?
SELECT 
country,
SUM(quantity) AS total_sales
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON f.customer_key = c.customer_key
GROUP BY country;
